enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":app")
include(":styleguide")
include(":commons-test")
include(":feature:main")
include(":infra:api-caller")
include(":infra:network:public")
include(":infra:network:impl")
include(":infra:action-dispatcher")
include(":design-system:view-state")
include(":design-system:illustration")
include(":design-system:tokens")
include(":domain:profile")
include(":server-driven-ui:cards-ui")
include(":server-driven-ui:cards-model")
include(":server-driven-ui:cards-processor-public")
